### ISSUE TITLE
+- 12 Volt Schaltung

### ISSUE THREAD

**Issue by Agilitytime** [kepppfeff/Ladebox-2#1]
Hallo Keppfeff,

erstmal herzlichen Glückwunsch zu deinem tollen Projekt.

Ich habe eine Frage zu dem Schaltplan.
Müsste bei "Ausgabe des + - 12 V Pwm Signals nicht auch ein - 12 V an die schaltung gehen und nicht 2 mal + 12 volt?

Lieben Dank,
Basti

**Comment by kepppfeff** [comment]
Hallo Basti,
die beiden +12V oben im Schaltplan sind korrekt. Der Komparator LM393 ist ja mit Pin 4 an -12V angeschlossen (Komponente U4C) und schaltet diese an die Ausgänge (Pin 1 und 7) durch :-) 
Freundliche Grüße Michi
